version: 0.2

env:
  parameter-store:
    APPSYNC_API_KEY: APPSYNC_API_KEY
    APPSYNC_URL: APPSYNC_URL
    DISCORD_API_KEY: DISCORD_API_KEY
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:  
    commands:
      - npm install
  post_build:
    commands:
      - export APPSYNC_API_KEY=$(aws ssm get-parameters --region eu-west-1 --names APPSYNC_API_KEY --query Parameters[0].Value)
      - export APPSYNC_URL=$(aws ssm get-parameters --region eu-west-1 --names APPSYNC_URL --query Parameters[0].Value)
      - export DISCORD_API_KEY=$(aws ssm get-parameters --region eu-west-1 --names DISCORD_API_KEY --query Parameters[0].Value)

artifacts:
  files:
    - '**/*'