version: 0.2

env:
  parameter-store:
    APPSYNC_API_KEY: "/CodeBuild/APPSYNC_API_KEY"
    APPSYNC_URL: "/CodeBuild/APPSYNC_URL"
    DISCORD_API_KEY: "/CodeBuild/DISCORD_API_KEY"

phases:

  install:
    runtime-versions:
      nodejs: 10

  build:
    commands:
      - export APPSYNC_API_KEY=APPSYNC_API_KEY
      - export APPSYNC_URL=APPSYNC_URL
      - export DISCORD_API_KEY=DISCORD_API_KEY

  pre_build:  
    commands:
      - npm install
      
artifacts:
  files:
    - '**/*'